Bottom Bar e Tela de enviar imagem.
SmartMeat-UnB/smartmeat pull request #18
Opened 2019-09-18 00:04 UTC by joao4018

2019-09-20 01:46 UTC, gabrielziegler3 commented
O sistema esta crashando ao tentar fazer o crop da imagem.

2019-09-20 01:57 UTC, gabrielziegler3 commented
```E/AndroidRuntime(24891): FATAL EXCEPTION: main
E/AndroidRuntime(24891): Process: com.example.smartmeat, PID: 24891
E/AndroidRuntime(24891): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=69, result=0, data=null} to activity {com.example.smartmeat/com.example.smartmeat.MainActivity}: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(24891): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4419)
E/AndroidRuntime(24891): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4461)
E/AndroidRuntime(24891): 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
E/AndroidRuntime(24891): 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
E/AndroidRuntime(24891): 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
E/AndroidRuntime(24891): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
E/AndroidRuntime(24891): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(24891): 	at android.os.Looper.loop(Looper.java:201)
E/AndroidRuntime(24891): 	at android.app.ActivityThread.main(ActivityThread.java:6806)
E/AndroidRuntime(24891): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(24891): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
E/AndroidRuntime(24891): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
E/AndroidRuntime(24891): Caused by: java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(24891): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:151)
E/AndroidRuntime(24891): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.success(MethodChannel.java:225)
E/AndroidRuntime(24891): 	at vn.hunghd.flutter.plugins.imagecropper.ImageCropperDelegate.onActivityResult(ImageCropperDelegate.java:106)
E/AndroidRuntime(24891): 	at io.flutter.app.FlutterPluginRegistry.onActivityResult(FlutterPluginRegistry.java:204)
E/AndroidRuntime(24891): 	at io.flutter.app.FlutterActivityDelegate.onActivityResult(FlutterActivityDelegate.java:132)
E/AndroidRuntime(24891): 	at io.flutter.app.FlutterActivity.onActivityResult(FlutterActivity.java:142)
E/AndroidRuntime(24891): 	at android.app.Activity.dispatchActivityResult(Activity.java:7590)
E/AndroidRuntime(24891): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4412)
E/AndroidRuntime(24891): 	... 11 more
I/Process (24891): Sending signal. PID: 24891 SIG: 9
```

2019-09-20 02:05 UTC, gabrielziegler3 requested changes
Arrumar crash.

2019-09-21 19:57 UTC, joao4018 commented
Nao tem crash, o Flutter recentemente atualizou, verifique a atualizacao e se continuar crashando rode o seguinte comando, flutter clean project

2019-09-24 03:36 UTC, closed without merging